
[tool.isort]
profile = "black"

[tool.black]
line-length = 88


[tool.pyright]
include = ["app"]
exclude = ["**/__pycache__"]
venvPath = "."
venv = "venv"

[tool.bandit]
exclude_dirs = ["venv", ".venv"]

[tool.bandit.B101]
skips = ["tests/*"]
